name: "ginforum"
mode: "dev"
port: 8080
version: "v0.0.1"
snowflake_start_time: "2023-02-01"
snowflake_machine_id: 1

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 300
  max_age: 30
  max_backups: 7
mysql:
  host: "mysql5730"
  port: 3306
  user: "root"
  password: "root2334"
  dbname: "gin_forum"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: "redis"
  port: 6379
  password: ""
  db: 0
  pool_size: 100